# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-13 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
