# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20190313_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
