# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20190313_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
