# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20190316_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='txt',
            field=models.FileField(default=0, upload_to='pic_folder'),
            preserve_default=False,
        ),
    ]
