# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_fileupload_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='txt',
        ),
    ]
